# -*- coding: utf-8 -*-
"""OCR_FreelancingBootcamp_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sh_Vc6wwtSzdZQvxDKjLsTOKBOg44KLc
"""

!pip install -q keras-ocr

import keras_ocr
import matplotlib.pyplot as plt

pipeline = keras_ocr.pipeline.Pipeline()

images = [
    keras_ocr.tools.read(img) for img in [
        '/content/drive/MyDrive/OCR Project Freelancing Bootcamp/Image1.jpg',
        '/content/drive/MyDrive/OCR Project Freelancing Bootcamp/Image2.jpg',
        '/content/drive/MyDrive/OCR Project Freelancing Bootcamp/Image3.jpg'
    ]
]

len(images)

plt.figure(figsize = (10,20))
plt.imshow(images[0])

plt.figure(figsize = (10,20))
plt.imshow(images[1])

plt.figure(figsize = (10,20))
plt.imshow(images[2])

prediction_groups = pipeline.recognize(images)

fig, axs = plt.subplots(nrows=len(images), figsize=(10, 20))
for ax, image, predictions in zip(axs, images, prediction_groups):
    keras_ocr.tools.drawAnnotations(image=image,
                                    predictions=predictions,
                                    ax=ax)

detector = keras_ocr.detection.Detector()
recognizer = keras_ocr.recognition.Recognizer()

pipline = keras_ocr.pipeline.Pipeline(detector=detector, recognizer=recognizer)
predection = pipeline.recognize(images)

predection